### ISSUE TITLE
Towscript issue

### ISSUE THREAD

**Issue by Zionzyee** [qbcore-framework/qb-towjob#28]
when you try to drop of the vehicle it doesn't complete the job

**Comment by Maxryodric** [comment]
this script worked in previous versions. it was possible to hand over the evacuated car
but now it doesn't work, I understand that they messed up when they moved the impound lot to another place

**Comment by tom-osborne** [comment]
Closed as duplicate of #31 

Hi all, it sounds like you are not quite delivering the vehicle to the correct location. The return location is shown on the map with a blip, you need to make sure the rear of the truck is close to this location when you untow the vehicle. If you get the positioning correct, you will get a success notification and payment.
