### ISSUE TITLE
[BUG] Not paying when dropping car off

### ISSUE THREAD

**Issue by brynnie1** [qbcore-framework/qb-towjob#31]
**Describe the bug**
We get a tow truck and do the command /npc
We drive to location put car on back of flatbed
Take car to the compund on where it needs to drop it off. However there is no marker on floor to say where exactly it needs dropping.  We then take car off flatbed, but nothing happens. Car doesn't delete and no payment for doing the job. 

Have 3rd eye set to = true but still not able to interact with either car or location

**Expected behavior**
As far as im aware car when dropping off at location / off the flatbed should delete the car/ impound it but doesn't. When interacting with the TowHQ to get paid it says you haven't done the work. 

**Questions (please complete the following information):**
 - When you last updated: 3days ago to be certain, but script hasnt been updated in some time
 - Are you using custom resource? which ones? Standard qb-target
 - Have you renamed `qb-` to something custom? No

**Comment by tom-osborne** [comment]
> **Describe the bug** We get a tow truck and do the command /npc We drive to location put car on back of flatbed Take car to the compund on where it needs to drop it off. However there is no marker on floor to say where exactly it needs dropping. We then take car off flatbed, but nothing happens. Car doesn't delete and no payment for doing the job.
> 
> Have 3rd eye set to = true but still not able to interact with either car or location
> 
> **Expected behavior** As far as im aware car when dropping off at location / off the flatbed should delete the car/ impound it but doesn't. When interacting with the TowHQ to get paid it says you haven't done the work.
> 
> **Questions (please complete the following information):**
> 
> * When you last updated: 3days ago to be certain, but script hasnt been updated in some time
> * Are you using custom resource? which ones? Standard qb-target
> * Have you renamed `qb-` to something custom? No

Hi @brynnie1 it sounds like you are not quite delivering the vehicle to the correct location. The return location is shown on the map with a blip, you need to make sure the rear of the truck is close to this location when you untow the vehicle. If you get the positioning correct, you will get a success notification and payment.

**Comment by tom-osborne** [comment]
Added a marker for the drop-off position to make it easier to get right. See #43
