### ISSUE TITLE
[BUG] Motorcycle not towable

### ISSUE THREAD

**Issue by GhostLegionRP** [qbcore-framework/qb-towjob#32]
When you try to tow a motorcycle or scooter it wont work

**Comment by tom-osborne** [comment]
![image](https://user-images.githubusercontent.com/96954031/179419448-b5315030-28b7-4909-91ab-c4192ac89ff6.png)

It is a little bit tricky, but it does work with a motorcycle. I recommend standing the bike up when trying to tow and make sure you are looking at the bike.
