### ISSUE TITLE
[BUG] Teleporting in vehicle when approaching blip

### ISSUE THREAD

**Issue by VoltaGoofy** [qbcore-framework/qb-towjob#44]
Hey! Today we went out testing the qb-towjob. and everything works perfect.

but on the moment we approach the tow_blip for towing the specific vehicle we getting teleported into the car that needs to be towed its very strange. 

you just get teleported out of your flatbed and get teleported into to vehicle that needs to be towed.

Hope this issue get fixed <3

King regards.

Bryan | Binnenlander

**Comment by tom-osborne** [comment]
> Hey! Today we went out testing the qb-towjob. and everything works perfect.
> 
> but on the moment we approach the tow_blip for towing the specific vehicle we getting teleported into the car that needs to be towed its very strange.
> 
> you just get teleported out of your flatbed and get teleported into to vehicle that needs to be towed.
> 
> Hope this issue get fixed <3
> 
> King regards.
> 
> Bryan | Binnenlander

Hi @VoltaGoofy do you have a video of this? Can you explain the steps to replicate? Thanks

**Comment by VoltaGoofy** [comment]
I can not send a video over on ghub! i will contact you on discord! Under the name: Bryan | Binnenlander#0001

**Comment by VoltaGoofy** [comment]
https://streamable.com/5edmwq


here is the video!
