### ISSUE TITLE
Vehicles Not Spawning

### ISSUE THREAD

**Issue by b1uedr4gon** [qbcore-framework/qb-towjob#50]
**Describe the bug**
When going to a vehicle blip to tow it the vehicle does not spawn

**To Reproduce**
1. Go and get the Tow Job
2. Go to the Tow HQ and take out a flatbed
3. Use your radial menu and go to work then "Toggle NPC"
4. Drive to the marked blip 
5. On Arrival No vehicle is present

**Expected behavior**
I would expect to pick up the Tow job , go to the HQ , get the truck , toggle npc's , drive to the blip and find the vehicle present and be able to tow it

**Screenshots**

**Questions (please complete the following information):**
 - Update Today
 - standard qb-towing
 - i have not renamed any of the qb-files or events

**Comment by tom-osborne** [comment]
@b1uedr4gon please make sure you have updated your core recently. The towjob uses the server sided vehicle spawns, so will only work with recent core updates.

**Comment by b1uedr4gon** [comment]
> @b1uedr4gon please make sure you have updated your core recently. The towjob uses the server sided vehicle spawns, so will only work with recent core updates.

This did indeed solve the problem
