### ISSUE TITLE
towing cars [BUG]

### ISSUE THREAD

**Issue by hybridgamer** [qbcore-framework/qb-towjob#55]
i can tow cars as mechanic and tow but my other members of my server canot tow i'm the only one what can i do

**Comment by NeonLifeRPde** [comment]
Same

**Comment by nzkfc** [comment]
Same here, we actually could not do it with qb-towjob as our Pheonix Anti-cheat was doing something to block it, I added the event to the whitelist and it fixed it.

Then 1 week later they say some cars can't go on the back of the tow truck, such as player-owned cars, but some AI ones work fine.

This function needs some love.

**Comment by nzkfc** [comment]
Seems that player cars won't go on unless you have the key. I also noticed you can't /depot the cars even if you have the keys.

https://youtu.be/v7eELKGm6FA

https://youtu.be/XG1Puwp-7v8

**Comment by nzkfc** [comment]
Anyone having issues with this? Been trying to see if it's just QB or something related like an anti-cheat or some other script.

**Comment by DosKit** [comment]
Best Bet would be to do example below to request ownership before the attach puts it onto the towtruck or getting into the driver seat before you try to tow it. This Sets you as the entity owner. 

`NetworkRequestControlOfEntity(vehicle)
while not NetworkHasControlOfEntity(vehicle) do Wait(0) end`

**Comment by nzkfc** [comment]
Eh I just gave up and replaced the script with an-tow job as it took her a
night to resolve it and clean up the entire script.

**Comment by The-Goat-Dev** [comment]
@hybridgamer , Are you still experiencing the problem ؟

**Comment by coleus216** [comment]
> 誠にの策は、以下の例を実行して、アタッチがレッカー車に乗る前に、またはレッカー車の運転席に乗る前に、レッカー車を牽引しようとする前に所有権をリクエストすることです。がエンティティの所有者として設定されます。
> 
> `NetworkRequestControlOfEntity(vehicle) while not NetworkHasControlOfEntity(vehicle) do Wait(0) end`

Does this still work?
I would like to know if there is a line to insert.

**Comment by nzkfc** [comment]
Just replace this with an-towjob

**Comment by coleus216** [comment]
thank you!
I was able to do everything perfectly!
