### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Blaze0341** [qbcore-framework/qb-towjob#57]
**Describe the bug**
While running tow job with NPC, every time a vehicle is located, you are unable to tow it. It states: "This is not the right vehicle" even though it is at the location specified and the only car around without NPCs in it. Have done this on several occasions to find the right vehicle. All return the same result.

There are no Console errors.

**Expected behavior**
Car is put on the back of the faltbed and the mission continues

**Screenshots**
![image](https://user-images.githubusercontent.com/99755932/205710091-12f4a22a-d921-440a-ad22-da35da28361f.png)

**Questions (please complete the following information):**
 - When you last updated: 12/5/2022
 - Are you using custom resource? which ones? Yes, quite a few. We also have swapped out the default cars for other ones. However I have updated those names in the Config file.
 - Have you renamed `qb-` to something custom? No
 - 
**Additional context**
Cant think of anything.

**Comment by xZToxicZx** [comment]
I had the same issue, turns out you need to get out of the truck and go up to the vehicle.
