### ISSUE TITLE
[BUG] "Tow Vehicle" not working

### ISSUE THREAD

**Issue by nzkfc** [qbcore-framework/qb-towjob#58]
**Describe the bug**
Noticed recently our tow yard workers cannot load any vehicles onto the flatbed, the option in qb-radialmenu is there to tow, but it doesn't do anything. I added a print to the RegisterNetEvent('qb-tow:client:TowVehicle', function() event and it's being triggered but no error in f8 or console.

https://i.imgur.com/lDihMYo.png

**To Reproduce**
1. Get tow job
2. Get work vehicle
3. Drive to the front a car you want to tow
4. F1 and then choose work and then tow vehicle
5. nothing happens

**Expected behavior**
Car usually get put on the back

**Screenshots**

**Questions (please complete the following information):**
 - When you last updated: Today for qb-towjob (qb framework is a month+ old in terms of updates
 - Are you using custom resource? which ones? a few 
 - Have you renamed `qb-` to something custom? No

**Additional context**
Started happening recently, noticed a few bugs happening since a recent FiveM update.

**Comment by mfjosh** [comment]
I am having the same issue. the car you are attempting to tow does not move to the flatbed, however when driving the flat bed the towtruck acts as if it has a load.

**Comment by nzkfc** [comment]
Just pulled a fresh qb-core city:
https://i.imgur.com/SedTCbv.jpeg

Same issue.
